import { z } from "zod";
import type { EngineeringFormState, FireTheftFormState, FormState, GeneralAccidentFormState, HealthFormState, TravelFormState } from "./types";

const requiredText = (message: string) => z.string().trim().min(1, message);

export const createSchema = (messages: {
  fieldRequired: string;
}) =>
  z.object({
    fullName: requiredText(messages.fieldRequired),
    phone: requiredText(messages.fieldRequired),
    email: z.string(),
    nationalId: requiredText(messages.fieldRequired),
    address: requiredText(messages.fieldRequired),
    city: requiredText(messages.fieldRequired),
    vehicleType: requiredText(messages.fieldRequired),
    manufacturer: requiredText(messages.fieldRequired),
    model: requiredText(messages.fieldRequired),
    year: requiredText(messages.fieldRequired),
    color: requiredText(messages.fieldRequired),
    plateNumber: requiredText(messages.fieldRequired),
    chassisNumber: requiredText(messages.fieldRequired),
    engineNumber: requiredText(messages.fieldRequired),
    estimatedValue: requiredText(messages.fieldRequired),
    notes: z.string(),
    confirmed: z.boolean(),
  });

export const initialForm: FormState = {
  fullName: "",
  phone: "",
  email: "",
  nationalId: "",
  address: "",
  city: "",
  vehicleType: "",
  manufacturer: "",
  model: "",
  year: "",
  color: "",
  plateNumber: "",
  chassisNumber: "",
  engineNumber: "",
  estimatedValue: "",
  notes: "",
  confirmed: false,
};

export const createEngineeringSchema = (messages: {
  fieldRequired: string;
}) =>
  z.object({
    fullName: requiredText(messages.fieldRequired),
    mobile: requiredText(messages.fieldRequired),
    email: z.string(),
    nationalId: z.string(),
    address: z.string(),
    city: z.string(),
    projectName: requiredText(messages.fieldRequired),
    projectType: requiredText(messages.fieldRequired),
    projectLocation: requiredText(messages.fieldRequired),
    contractValue: requiredText(messages.fieldRequired),
    currency: requiredText(messages.fieldRequired),
    insuranceType: requiredText(messages.fieldRequired),
    startDate: z.string(),
    endDate: z.string(),
    contractorName: z.string(),
    ownerName: z.string(),
    riskDetails: z.string(),
    notes: z.string(),
    confirmed: z.boolean(),
  });

export const initialEngineeringForm: EngineeringFormState = {
  fullName: "",
  mobile: "",
  email: "",
  nationalId: "",
  address: "",
  city: "Baghdad",
  projectName: "",
  projectType: "",
  projectLocation: "",
  contractValue: "",
  currency: "IQD",
  insuranceType: "Contractors All Risks",
  startDate: "",
  endDate: "",
  contractorName: "",
  ownerName: "",
  riskDetails: "",
  notes: "",
  confirmed: false,
};

export const createHealthSchema = (messages: {
  fieldRequired: string;
}) =>
  z.object({
    fullName: requiredText(messages.fieldRequired),
    mobile: requiredText(messages.fieldRequired),
    email: z.string(),
    nationalId: requiredText(messages.fieldRequired),
    address: z.string(),
    city: requiredText(messages.fieldRequired),
    age: requiredText(messages.fieldRequired),
    gender: requiredText(messages.fieldRequired),
    planType: requiredText(messages.fieldRequired),
    coverageScope: requiredText(messages.fieldRequired),
    insuredMembersCount: requiredText(messages.fieldRequired),
    companyName: z.string(),
    occupation: z.string(),
    hasChronicConditions: z.boolean(),
    chronicConditions: z.string(),
    previousInsurance: z.boolean(),
    previousInsurer: z.string(),
    preferredHospitals: z.string(),
    coverageStartDate: z.string(),
    coverageEndDate: z.string(),
    estimatedAnnualPremium: z.string(),
    currency: requiredText(messages.fieldRequired),
    notes: z.string(),
    confirmed: z.boolean(),
  });

export const initialHealthForm: HealthFormState = {
  fullName: "",
  mobile: "",
  email: "",
  nationalId: "",
  address: "",
  city: "Baghdad",
  age: "",
  gender: "",
  planType: "Individual Health",
  coverageScope: "Iraq",
  insuredMembersCount: "1",
  companyName: "",
  occupation: "",
  hasChronicConditions: false,
  chronicConditions: "",
  previousInsurance: false,
  previousInsurer: "",
  preferredHospitals: "",
  coverageStartDate: "",
  coverageEndDate: "",
  estimatedAnnualPremium: "",
  currency: "IQD",
  notes: "",
  confirmed: false,
};

export const createFireTheftSchema = (messages: {
  fieldRequired: string;
}) =>
  z.object({
    fullName: requiredText(messages.fieldRequired),
    mobile: requiredText(messages.fieldRequired),
    email: z.string(),
    nationalId: requiredText(messages.fieldRequired),
    address: z.string(),
    city: requiredText(messages.fieldRequired),
    propertyType: requiredText(messages.fieldRequired),
    propertyUsage: requiredText(messages.fieldRequired),
    propertyAddress: requiredText(messages.fieldRequired),
    buildingValue: requiredText(messages.fieldRequired),
    contentsValue: z.string(),
    stockValue: z.string(),
    totalSumInsured: requiredText(messages.fieldRequired),
    currency: requiredText(messages.fieldRequired),
    coverageScope: requiredText(messages.fieldRequired),
    hasFireAlarm: z.boolean(),
    hasFireExtinguishers: z.boolean(),
    hasSecuritySystem: z.boolean(),
    notes: z.string(),
    confirmed: z.boolean(),
  });

export const initialFireTheftForm: FireTheftFormState = {
  fullName: "",
  mobile: "",
  email: "",
  nationalId: "",
  address: "",
  city: "Baghdad",
  propertyType: "Warehouse",
  propertyUsage: "",
  propertyAddress: "",
  buildingValue: "",
  contentsValue: "",
  stockValue: "",
  totalSumInsured: "",
  currency: "IQD",
  coverageScope: "Fire and theft",
  hasFireAlarm: false,
  hasFireExtinguishers: false,
  hasSecuritySystem: false,
  notes: "",
  confirmed: false,
};

export const createGeneralAccidentSchema = (messages: {
  fieldRequired: string;
}) =>
  z.object({
    fullName: requiredText(messages.fieldRequired),
    mobile: requiredText(messages.fieldRequired),
    email: z.string(),
    nationalId: requiredText(messages.fieldRequired),
    address: z.string(),
    city: requiredText(messages.fieldRequired),
    insuredName: requiredText(messages.fieldRequired),
    businessActivity: requiredText(messages.fieldRequired),
    accidentType: requiredText(messages.fieldRequired),
    coverageScope: requiredText(messages.fieldRequired),
    riskLocation: requiredText(messages.fieldRequired),
    riskCity: requiredText(messages.fieldRequired),
    employeesCount: requiredText(messages.fieldRequired),
    beneficiariesCount: z.string(),
    coverageLimit: requiredText(messages.fieldRequired),
    deductibleAmount: z.string(),
    estimatedAnnualWages: z.string(),
    currency: requiredText(messages.fieldRequired),
    riskDetails: z.string(),
    hasSafetyProgram: z.boolean(),
    previousClaims: z.boolean(),
    notes: z.string(),
    confirmed: z.boolean(),
  });

export const initialGeneralAccidentForm: GeneralAccidentFormState = {
  fullName: "",
  mobile: "",
  email: "",
  nationalId: "",
  address: "",
  city: "Baghdad",
  insuredName: "",
  businessActivity: "",
  accidentType: "Public liability",
  coverageScope: "General accident and third-party liability",
  riskLocation: "",
  riskCity: "Baghdad",
  employeesCount: "",
  beneficiariesCount: "0",
  coverageLimit: "",
  deductibleAmount: "",
  estimatedAnnualWages: "",
  currency: "IQD",
  riskDetails: "",
  hasSafetyProgram: false,
  previousClaims: false,
  notes: "",
  confirmed: false,
};

export const createTravelSchema = (messages: {
  fieldRequired: string;
}) =>
  z.object({
    fullName: requiredText(messages.fieldRequired),
    mobile: requiredText(messages.fieldRequired),
    email: z.string(),
    nationalId: requiredText(messages.fieldRequired),
    address: z.string(),
    city: requiredText(messages.fieldRequired),
    passportNumber: requiredText(messages.fieldRequired),
    dateOfBirth: requiredText(messages.fieldRequired),
    destinationCountry: requiredText(messages.fieldRequired),
    departureDate: requiredText(messages.fieldRequired),
    returnDate: requiredText(messages.fieldRequired),
    travelersCount: requiredText(messages.fieldRequired),
    tripPurpose: requiredText(messages.fieldRequired),
    coverageType: requiredText(messages.fieldRequired),
    coverageScope: requiredText(messages.fieldRequired),
    hasMedicalConditions: z.boolean(),
    medicalConditions: z.string(),
    emergencyContactName: z.string(),
    emergencyContactPhone: z.string(),
    estimatedPremium: z.string(),
    currency: requiredText(messages.fieldRequired),
    notes: z.string(),
    confirmed: z.boolean(),
  });

export const initialTravelForm: TravelFormState = {
  fullName: "",
  mobile: "",
  email: "",
  nationalId: "",
  address: "",
  city: "Baghdad",
  passportNumber: "",
  dateOfBirth: "",
  destinationCountry: "",
  departureDate: "",
  returnDate: "",
  travelersCount: "1",
  tripPurpose: "Tourism",
  coverageType: "Single trip",
  coverageScope: "Medical, travel delay, baggage loss",
  hasMedicalConditions: false,
  medicalConditions: "",
  emergencyContactName: "",
  emergencyContactPhone: "",
  estimatedPremium: "",
  currency: "IQD",
  notes: "",
  confirmed: false,
};
